### ISSUE TITLE
Make debootstrap   customizable

### ISSUE THREAD

**Issue by Mr-Pi** [stuvusIT/xen_vman#3]

**Comment by dasJ** [comment]
Just do it, no need to create an issue. Something like:

```yml
# defaults/main.yml

xen_vman_deboostrap_packages: systemd,systemd-sysv,openssh-server,python
```

```yml
# tasks/install_system.yml

# [SNIP]
- name: Install {{ vm.os.type }} {{ vm.os.version }} at {{ vm.host }} @{{ vm.org }}
  shell: debootstrap --variant minbase --include {{ xen_vman_deboostrap_pacakges }} {{ vm.os.version }} /mnt/vms/{{ vm.org }}-{{ vm.host }}
when: vm.os.type == "ubuntu"
# [SNIP]
```
